Add hlint and stylish-haskell checks.

diff --git a/.github/workflows/haskell.yml b/.github/workflows/haskell.yml
--- a/.github/workflows/haskell.yml
+++ b/.github/workflows/haskell.yml
@@ -10,8 +10,7 @@ permissions:
   contents: read
 
 jobs:
-  validate:
-    name: Validate
+  build:
     runs-on: ubuntu-latest
 
     steps:
@@ -62,3 +61,29 @@ jobs:
 
     - name: Build documentation
       run: cabal haddock all
+
+  hlint:
+    runs-on: ubuntu-latest
+
+    steps:
+    - uses: actions/checkout@v3
+
+    - name: 'Set up hlint'
+      uses: haskell/actions/hlint-setup@v2
+
+    - name: 'Run hlint'
+      uses: haskell/actions/hlint-run@v2
+      with:
+        path: src/
+        fail-on: warning
+
+  format:
+    runs-on: ubuntu-latest
+
+    steps:
+    - uses: actions/checkout@v3
+
+    - name: 'Run stylish-haskell'
+      run: |
+        curl -sL https://raw.github.com/haskell/stylish-haskell/master/scripts/latest.sh | sh -s -ri src
+        test -z "$( git status --porcelain src )" || echo "::error ::all files must be formatted with stylish-haskell"
